# Use an official Node runtime as the parent image
FROM node:16

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json or yarn.lock (if available)
COPY package*.json ./

# Install any needed packages in /app
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Navigate into the specific package directory
WORKDIR /app/apps/portfolio-web

# Install necessary dependencies
RUN npm install astro

# Build the app
RUN npm run build

COPY --from=build /app/out /app
RUN npm install --global http-server

EXPOSE 80
CMD ["http-server"]
